### ISSUE TITLE
raise error "undefined method `arel_table'" in rails 5

### ISSUE THREAD

**Issue by isuke** [zilkey/active_hash#151]
Error of "undefined method `arel_table'" has raised when I did following test.

```
# spec/associations/active_record_extensions_spec.rb
describe "#belongs_to_active_hash" do
  context "setting by id" do
    it "finds the correct records" do
      School.belongs_to_active_hash :city
      city = City.create
      school = School.create :city_id => city.id
      School.find_by(city: city).should == city
    end
  end
end
```

```
[] % bundle exec rspec spec/associations/active_record_extensions_spec.rb:207
Run options: include {:locations=>{"./spec/associations/active_record_extensions_spec.rb"=>[207]}}
F

Failures:

  1) ActiveHash::Base active record extensions ActiveHash::Associations::ActiveRecordExtensions #belongs_to_active_hash setting by id 
     Failure/Error: School.find_by(city: city)
     NoMethodError:
       undefined method `arel_table' for City:Class
     # ./lib/active_hash/base.rb:274:in `method_missing'
     # ./spec/associations/active_record_extensions_spec.rb:207:in `block (5 levels) in <top (required)>'

```

Thank you.

**Comment by syguer** [comment]
> School.find_by(city: city).should == city

`School.find_by` returns School instance. It is incorrect before an issue.

By the way, ActiveHash does not support `arel` behaviour. so you should do like this

```ruby
 School.find_by(city_id: city.id).should == school
```

If you want to write like your sample, pull request is welcome 😄 
Thanks.
