### ISSUE TITLE
Ruby 2.1.1 / Rails 4.1.0-rc1 - undefined method `create_reflection'

### ISSUE THREAD

**Issue by m5o** [zilkey/active_hash#87]
Don't know if you currently support this edge setup. With `ruby 2.1.1p76 (2014-02-24 revision 45161)` and `Rails 4.1.0.rc1`. 

I have this simple setup:

```rb
class Product < ActiveRecord::Base
  [...]
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :promotion_type
end
```

```rb
class PromotionType < ActiveHash::Base
  self.data = [
    { id: 1, name: "Standard" },
    { id: 2, name: "Featured" },
    { id: 3, name: "Bonus" },
  ]

  include ActiveHash::Associations
  has_many :products
end
```

i get the following error:

```
gems/active_hash-1.3.0/lib/associations/associations.rb:47:in `method': undefined method `create_reflection' for class `Class' (NameError)
	from /Users/bla/.rvm/gems/ruby-2.1.1@foobar/gems/active_hash-1.3.0/lib/associations/associations.rb:47:in `belongs_to_active_hash'
	from /Users/bla/code/foobar/app/models/product.rb:4:in `<class:Product>'
	from /Users/bla/code/foobar/app/models/product.rb:2:in `<top (required)>'
	from /Users/bla/.rvm/gems/ruby-2.1.1@foobar/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:247:in `require'
	from /Users/bla/.rvm/gems/ruby-2.1.1@foobar/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:247:in `block in require'
	from /Users/bla/.rvm/gems/ruby-2.1.1@foobar/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/bla/.rvm/gems/ruby-2.1.1@foobar/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:247:in `require'
	from /Users/bla/.rvm/gems/ruby-2.1.1@foobar/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:348:in `require_or_load'
	from /Users/bla/.rvm/gems/ruby-2.1.1@foobar/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:480:in `load_missing_constant'
	from /Users/bla/.rvm/gems/ruby-2.1.1@foobar/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:180:in `const_missing'
	from /Users/bla/code/foobar/spec/factories/products.rb:34:in `block in <top (required)>'
[...]
```

Currently i have no idea what could be wrong, did someone has a tipp on that topic?

**Comment by kbrock** [comment]
This seems to be resolved. Please reopen if this is still an issue.

Thanks
